apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions
  labels:
    app: github-actions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-actions
  template:
    metadata:
      labels:
        app: github-actions
    spec:
      containers:
        - name: github-actions
          image: REPOSITORY:TAG
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
            limits:
              cpu: 1000m
              memory: 256Mi
